services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports: 
    - "5173:5173"